### ISSUE TITLE
Error: 'USBD_MAX_POWER' undeclared here (not in a function)

### ISSUE THREAD

**Issue by Bauschlumpf** [zeleps/BootloaderZ#2]
Hello,

The SD card reader of my BTT GTR 1.0 board is defective. Flashing only works if you hold the card firmly pressed in. Therefore, I would like to use the alternative function via USB.

The following error occurs when compiling the bootloader:

Compiling .pio\build\genericSTM32F407VGT6\platforms\stm32f4xx\usbd_customhid.o
platforms\stm32f4xx\usbd_customhid.c:141:3: error: 'USBD_MAX_POWER' undeclared here (not in a function); did you mean 'USBD_SELF_POWERED'?
   USBD_MAX_POWER,                                     /* MaxPower 100 mA: this current is used for detecting Vbus */
   ^~~~~~~~~~~~~~
   USBD_SELF_POWERED
*** [.pio\build\genericSTM32F407VGT6\platforms\stm32f4xx\usbd_customhid.o] Error 1

I have adjusted the configuration according to the wiki https://github.com/zeleps/BootloaderZ/wiki/Configuring-a-BTT-GTR-1.0-for-automatic-flashing.

Alternatively, is it possible to flash without the alternative bootloader via USB using boot0 on R3 (pushbutton against 3.3V // wire to pin of an RPI) using _dfu-util -D [path to firmware binary]/firmware.bin --dfuse-address 0x08008000:leave_ ?

Thanks in advance
Bauschlumpf

**Comment by zeleps** [comment]
Hey @Bauschlumpf! I'm out of home for the weekend, and my access is limited, so all I can do until Monday is guesswork.

The compilation error is probably a library version issue, please make sure your stm32cube libraries in platformio are up to date. If that doesn't work, I'll be able to help you on Monday, when I get back.

If you don't want to use the boot0 pin method, the only way is to buy an st-link device. I don't think there is any other alternative.

**Comment by Bauschlumpf** [comment]
Hello @zeleps.

Thank you very much! With the update the problem is solved. I have never done updates in VS Studio code before.

So far I have used ST-Link Device only for blue and black pills. I find the idea with programming BTT GTR 1.0 with a RPi via serial port very handy.

Have a nice weekend

**Comment by zeleps** [comment]
Happy to hear that!

Do tell me if it all works out!

**Comment by Bauschlumpf** [comment]
Hello @zeleps.

I have now installed the bootloader with the help of the ST-Link device. Before that I had to do some family printing. Firmware updates for the GTR 1.0 now work via USB (DFU). I will also try it with a BTR E3-MINI V1.2 (STM32F103RCT6).

Thank you very much!!!
Bauschlumpf
